#!/bin/bash

CURDIR=`dirname $0`
SHARED=`dirname $CURDIR`/shared

cd $CURDIR

export CACHE=$SHARED/cache
mkdir -p $CACHE

exec carmel exec start_server --port=${PORT:-5000} \
  --interval=5 \
  --dir=$CURDIR \
  --signal-on-hup=QUIT \
  --status-file=$SHARED/pids/start_server.status \
  --pid-file=$SHARED/pids/start_server.pid \
  -- \
  starman -I$CURDIR/lib --preload-app --access-log=$CURDIR/log/access_log \
  $CURDIR/app-gw.psgi
