#!/bin/bash

CURDIR=`dirname $0`
SHARED=`dirname $CURDIR`/shared

cd $CURDIR

export PACKAGES_HISTORY_TXT=/var/www/cpanmetadb-data.plackperl.org/htdocs/packages.txt

exec carmel exec start_server --port=5000 \
  --dir=$CURDIR \
  --status-file=$SHARED/pids/start_server.status \
  --pid-file=$SHARED/pids/start_server.pid \
  -- \
  twiggy -I$CURDIR/lib --access-log=$CURDIR/log/access_log \
  $CURDIR/app-gw.psgi
