#!/usr/bin/env perl
use strict;
use warnings;
use CPAN::DistnameInfo;

my %seen;

while (<>) {
    chomp;
    if (/^ -[\w\_:]+ \s+ \S+ \s+ ([A-Z]\/[A-Z]{2}\/\S*) $/x) {
        next if $seen{$1}++;
        purge_key($1);
        purge_key(CPAN::DistnameInfo->new($1)->dist);
    }
}

sub purge_key {
    my $key = shift;

    warn "Purging by surrogate-key $key\n";

    system 'curl', '-s', '-o', '/dev/null',
      '-H', "Fastly-Key: $ENV{FASTLY_KEY}",
      '-X', 'POST',
      "https://api.fastly.com/service/$ENV{FASTLY_SERVICE_ID}/purge/$key";
}
