#!/usr/bin/env perl
use strict;
use warnings;
use CPAN::DistnameInfo;

my %seen;

my $purger = sub {
    my $key = shift;
    return if $seen{$key}++;

    warn "Purging by surrogate-key $key\n";

    system 'curl', '-s', '-o', '/dev/null',
      '-H', "Fastly-Key: $ENV{FASTLY_KEY}",
      '-X', 'POST',
      "https://api.fastly.com/service/$ENV{FASTLY_SERVICE_ID}/purge/$key";
};

while (<>) {
    chomp;
    if (/^ -[\w\_:]+ \s+ \S+ \s+ ([A-Z]\/[A-Z]{2}\/\S*) $/x) {
        $purger->($1);
        $purger->(CPAN::DistnameInfo->new($1)->dist);
    }
}
