#!/usr/bin/env perl
use strict;

while (<>) {
    chomp;
    if (/^ -[\w\_:]+ \s+ \S+ \s+ ([A-Z]\/[A-Z]{2}\/.*) $/x) {
        purge_key($1);
    }
}

sub purge_key {
    my $key = shift;

    warn "Purging by surrogate-key $key\n";

    system 'curl', '-s', '-o', '/dev/null',
      '-H', "Fastly-Key: $ENV{FASTLY_KEY}",
      '-X', 'POST',
      "https://api.fastly.com/service/$ENV{FASTLY_SERVICE_ID}/purge/$key";
}
