#!/bin/bash

mkdir -p $CACHE
(cd $CACHE && wget -q http://cpan.metacpan.org/modules/02packages.details.txt.gz -N)
gunzip -c $CACHE/02packages.details.txt.gz > $CACHE/02packages.details.txt

(cd $CACHE && wget -q http://cpanmetadb.plackperl.org/data/packages.txt.gz -N)
gunzip -c $CACHE/packages.txt.gz > $CACHE/packages.txt

export DSN=dbi:SQLite:dbname=$CACHE/pause.sqlite3
script/dumpsql.pl
